[project]
name = "azure-blobrepo-rpm"
description = "Functionality to create an RPM package repository in Azure Blob Storage"
license = "MIT"
version = "0.1.0"
readme = "README.md"
authors = [{name = "Max Dymond", email = "max.dymond@alianza.com"}]
requires-python = '>=3.13,<4.0'
dependencies = ['azure-functions (>=2.3.0,<2.4.0)', 'azure-identity (>=1.19.0,<2.0.0)', 'azure-storage-blob (>=12.24.0,<13.0.0)', 'createrepo-c (>=1.2.1,<2.0.0)', 'rpmfile (>=2.1.0,<3.0.0)', 'zstandard (>=0.25.0,<0.26.0)']

[project.scripts]
create-resources = "azure_blobrepo_rpm.tooling.create_resources:run"

[tool.poetry]
requires-poetry = '>=2.0'

[tool.poetry.dependencies]
python = "^3.13"

[tool.poetry.group.dev.dependencies]
mypy = "2.3.1"
ruff = "0.16.6"
pytest = "9.1.1"

[build-system]
requires = ['poetry-core (>=2.0)']
build-backend = "poetry.core.masonry.api"

[tool.mypy]
files = ["function_app.py", "azure_blobrepo_rpm", "tests"]

[[tool.mypy.overrides]]
module = ["rpmfile.*", "createrepo_c.*"]
ignore_missing_imports = true
